# Generated by Django 2.0.1 on 2018-02-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180215_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
    ]
