# Generated by Django 2.0.2 on 2018-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20180222_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='news_in_category', to='feed.Category'),
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='news_in_source', to='feed.Source'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(default='', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='feed.Tag'),
        ),
        migrations.AlterField(
            model_name='source',
            name='category',
            field=models.ForeignKey(on_delete='CASCADE', related_name='sources', to='feed.Category'),
        ),
    ]
