# Generated by Django 2.0.2 on 2018-03-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_remove_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='news',
            field=models.ForeignKey(on_delete='CASCADE', related_name='article_images', to='feed.News'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.TextField(default='', max_length=500),
        ),
    ]
