# Generated by Django 2.0.2 on 2018-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20180315_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='articles_page',
            field=models.TextField(default='', max_length=400),
        ),
    ]
